# -*- coding: utf-8 -*-
"""
Created on Sun Sep 25 17:38:57 2016

@author: zefeng
"""
import time
import os
i= os.system('cls')
time.sleep(1)
print("######     ######")
print("    #      #     ")
print("   #       ######")
print("  #        #     ")
print(" #####     #     ")
time.sleep(0.2)
i= os.system('cls')
print(" ######     ######")
print("     #      #     ")
print("    #       ######")
print("   #        #     ")
print("  #####     #     ")
time.sleep(0.2)
i= os.system('cls')
print("  ######     ######")
print("      #      #     ")
print("     #       ######")
print("    #        #     ")
print("   #####     #     ")
time.sleep(0.2)
i= os.system('cls')
print("   ######     ######")
print("       #      #     ")
print("      #       ######")
print("     #        #     ")
print("    #####     #     ")
time.sleep(0.2)
i= os.system('cls')
print("    ######     ######")
print("        #      #     ")
print("       #       ######")
print("      #        #     ")
print("     #####     #     ")
time.sleep(0.2)
i= os.system('cls')
print("     ######     ######")
print("         #      #     ")
print("        #       ######")
print("       #        #     ")
print("      #####     #     ")
time.sleep(0.2)
i= os.system('cls')
print("      ######     ######")
print("          #      #     ")
print("         #       ######")
print("        #        #     ")
print("       #####     #     ")
time.sleep(0.2)
i= os.system('cls')
print("       ######     ######")
print("           #      #     ")
print("          #       ######")
print("         #        #     ")
print("        #####     #     ")
time.sleep(0.2)
i= os.system('cls')
print("        ######     ######")
print("            #      #     ")
print("           #       ######")
print("          #        #     ")
print("         #####     #     ")
time.sleep(0.2)
i= os.system('cls')
print("         ######     ######")
print("             #      #     ")
print("            #       ######")
print("           #        #     ")
print("          #####     #     ")
time.sleep(0.2)
i= os.system('cls')
print("          ######     ######")
print("              #      #     ")
print("             #       ######")
print("            #        #     ")
print("           #####     #     ")
time.sleep(0.2)
i= os.system('cls')
print("           ######     ######")
print("               #      #     ")
print("              #       ######")
print("             #        #     ")
print("            #####     #     ")

